/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'audit': RouteRecordInfo<'audit', '/audit', Record<never, never>, Record<never, never>>,
    'circuit-import': RouteRecordInfo<'circuit-import', '/circuit-import', Record<never, never>, Record<never, never>>,
    'circuits': RouteRecordInfo<'circuits', '/circuits', Record<never, never>, Record<never, never>>,
    'device-import': RouteRecordInfo<'device-import', '/device-import', Record<never, never>, Record<never, never>>,
    'devices': RouteRecordInfo<'devices', '/devices', Record<never, never>, Record<never, never>>,
    'devices-id': RouteRecordInfo<'devices-id', '/devices/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'discovery': RouteRecordInfo<'discovery', '/discovery', Record<never, never>, Record<never, never>>,
    'isp-providers': RouteRecordInfo<'isp-providers', '/isp-providers', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'notifications': RouteRecordInfo<'notifications', '/notifications', Record<never, never>, Record<never, never>>,
    'reports': RouteRecordInfo<'reports', '/reports', Record<never, never>, Record<never, never>>,
    'security-two-factor-setup': RouteRecordInfo<'security-two-factor-setup', '/security/two-factor-setup', Record<never, never>, Record<never, never>>,
    'sites': RouteRecordInfo<'sites', '/sites', Record<never, never>, Record<never, never>>,
    'ssh-credentials': RouteRecordInfo<'ssh-credentials', '/ssh-credentials', Record<never, never>, Record<never, never>>,
    'syslog': RouteRecordInfo<'syslog', '/syslog', Record<never, never>, Record<never, never>>,
    'topology': RouteRecordInfo<'topology', '/topology', Record<never, never>, Record<never, never>>,
    'users': RouteRecordInfo<'users', '/users', Record<never, never>, Record<never, never>>,
    'vulnerabilities': RouteRecordInfo<'vulnerabilities', '/vulnerabilities', Record<never, never>, Record<never, never>>,
    'wallboard': RouteRecordInfo<'wallboard', '/wallboard', Record<never, never>, Record<never, never>>,
  }
}
